function safeIdentifier(name) {
  const identifier = name.replace(/[^A-Za-z0-9_$]/g, '_');
  return /^[A-Za-z_$]/.test(identifier) ? identifier : `_${identifier}`;
}

function stableJson(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(stableJson).join(',')}]`;
  return `{${Object.entries(value)
    .filter(([, item]) => item !== undefined)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([key, item]) => `${JSON.stringify(key)}:${stableJson(item)}`)
    .join(',')}}`;
}

function sourceRef(node, extra = {}) {
  return {
    semanticNodeId: node.id,
    semanticNodeKind: node.kind,
    semanticNodeName: node.name,
    ...extra
  };
}

export function toJavaScriptAst(document, options = {}) {
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-javascript.';
  const declarations = [];
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'lattice') {
      declarations.push({
        kind: 'exportConst',
        name: `${safeIdentifier(node.name)}Lattice`,
        value: {
          name: node.name,
          carrier: node.carrier,
          laws: node.laws ?? [],
          frontierCrdt: node.frontierCrdt
        },
        freeze: true,
        sourceRef: sourceRef(node)
      });
    }
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'capability') {
      declarations.push({
        kind: 'exportConst',
        name: `${safeIdentifier(node.name)}Capability`,
        value: {
          capability: node.capability,
          category: node.category,
          input: node.input,
          returns: node.returns,
          effects: node.effects ?? [],
          resources: node.resources ?? [],
          adapters: node.adapters ?? [],
          unsupportedTargets: node.unsupportedTargets ?? []
        },
        freeze: true,
        sourceRef: sourceRef(node)
      });
    }
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'entity' || node.kind === 'type') {
      declarations.push({
        kind: 'exportConst',
        name: `${safeIdentifier(node.name)}Schema`,
        value: {
          kind: node.kind,
          name: node.name,
          fields: node.fields ?? [],
          variants: node.variants ?? []
        },
        freeze: true,
        sourceRef: sourceRef(node, { regionIds: (node.fields ?? []).map((field) => field.id) })
      });
    }
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'view') {
      declarations.push({
        kind: 'exportConst',
        name: `${safeIdentifier(node.name)}View`,
        value: { name: node.name, reads: node.reads ?? [], dispatches: node.dispatches ?? [], props: node.props ?? [], events: node.events ?? [], renders: node.renders ?? [] },
        freeze: true,
        sourceRef: sourceRef(node, { regionIds: [...(node.props ?? []).map((prop) => prop.id), ...(node.events ?? []).map((event) => event.id), ...(node.renders ?? []).map((render) => render.id)] })
      });
    }
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'extern') {
      declarations.push({ kind: 'exportFunction', name: safeIdentifier(node.name), params: [], body: [`throw new Error(${JSON.stringify(`Extern ${node.name} must be provided by the host runtime.`)});`], sourceRef: sourceRef(node) });
    }
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'action') {
      declarations.push({ kind: 'exportFunction', name: safeIdentifier(node.name), params: ['state', 'input', 'env = {}'], body: ['void state;', 'void input;', 'void env;', 'return [];'], sourceRef: sourceRef(node) });
    }
  }
  return { kind: 'javascript.module', banner, declarations };
}

export function renderJavaScriptAst(ast) {
  return renderJavaScriptAstWithSourceMap(ast).code;
}

export function renderJavaScriptAstWithSourceMap(ast, options = {}) {
  const lines = [];
  const mappings = [];
  const target = normalizeTarget(options, 'javascript');
  lines.push(`// ${ast.banner}`, '');
  ast.declarations.forEach((declaration, index) => {
    const startLine = lines.length + 1;
    const startIndex = lines.length;
    renderJavaScriptDeclaration(lines, declaration);
    const generatedSpan = declarationBlockSpan(lines, startIndex, startLine, declaration, target, options.targetPath);
    if (declaration.sourceRef?.semanticNodeId && generatedSpan) {
      mappings.push(sourceMapMapping(declaration, index, generatedSpan, target, options, 'javascript-renderer-declaration-block'));
    }
  });
  const code = `${lines.join('\n').trimEnd()}\n`;
  return {
    code,
    sourceMap: sourceMapEnvelope(ast, mappings, target, options, 'javascript', 'javascript-renderer-declaration-block')
  };
}

function renderJavaScriptDeclaration(lines, declaration) {
    if (declaration.kind === 'exportConst') {
      const value = declaration.freeze ? `Object.freeze(${stableJson(declaration.value)})` : stableJson(declaration.value);
      lines.push(`export const ${declaration.name} = ${value};`, '');
    }
    if (declaration.kind === 'exportFunction') {
      lines.push(`export function ${declaration.name}(${declaration.params.join(', ')}) {`);
      for (const statement of declaration.body) lines.push(`  ${statement}`);
      lines.push('}', '');
    }
}

export function emitJavaScript(document, options = {}) {
  return renderJavaScriptAst(toJavaScriptAst(document, options));
}

export function emitJavaScriptWithSourceMap(document, options = {}) {
  const ast = toJavaScriptAst(document, options);
  const result = renderJavaScriptAstWithSourceMap(ast, {
    sourceMapId: options.sourceMapId ?? `sourcemap_${idFragment(document.id)}_javascript`,
    ...options
  });
  return { ...result, ast };
}

function declarationBlockSpan(lines, startIndex, startLine, declaration, target, targetPath) {
  let endIndex = lines.length - 1;
  while (endIndex >= startIndex && lines[endIndex] === '') endIndex -= 1;
  if (endIndex < startIndex) return undefined;
  return definedObject({
    path: targetPath,
    target,
    targetPath,
    generatedName: declaration.name,
    startLine,
    startColumn: 1,
    endLine: endIndex + 1,
    endColumn: lines[endIndex].length + 1
  });
}

function normalizeTarget(options, language) {
  return definedObject({
    ...(options.target ?? {}),
    language: options.target?.language ?? language,
    emitPath: options.target?.emitPath ?? options.targetPath
  });
}

function sourceMapMapping(declaration, index, generatedSpan, target, options, strategy) {
  return definedObject({
    id: `map_${idFragment(declaration.sourceRef.semanticNodeId)}_${index}`,
    semanticNodeId: declaration.sourceRef.semanticNodeId,
    nativeSourceId: options.nativeSourceId,
    semanticSymbolId: options.semanticSymbolIdsBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
    semanticOccurrenceId: options.semanticOccurrenceIdsBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
    sourceSpan: options.sourceSpansBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
    generatedSpan,
    target,
    generatedName: declaration.name,
    evidenceIds: options.evidence?.map((record) => record.id),
    lossIds: options.lossIdsBySemanticNodeId?.[declaration.sourceRef.semanticNodeId],
    precision: 'declaration',
    metadata: {
      generatedSpanStrategy: strategy,
      sourceMapImplication: 'Generated span covers the emitted declaration block and is not token exact.',
      semanticIndexImplication: 'Mapping is anchored by semanticNodeId; symbol and occurrence ids are optional caller-provided links.',
      lossAccountingImplication: 'No loss ids are inferred by the printer; caller-provided loss ids are copied when available.',
      mergeReadinessImplication: 'Suitable for declaration-level overlap review, not fine-grained token merge admission.',
      semanticNodeKind: declaration.sourceRef.semanticNodeKind,
      semanticNodeName: declaration.sourceRef.semanticNodeName,
      regionIds: declaration.sourceRef.regionIds
    }
  });
}

function sourceMapEnvelope(ast, mappings, target, options, language, strategy) {
  return definedObject({
    kind: 'frontier.lang.sourceMap',
    version: 1,
    id: options.sourceMapId ?? `sourcemap_${idFragment(ast.kind)}_${language}`,
    sourcePath: options.sourcePath,
    sourceHash: options.sourceHash,
    target,
    targetPath: options.targetPath,
    targetHash: options.targetHash,
    semanticIndexId: options.semanticIndexId,
    universalAstId: options.universalAstId,
    nativeAstId: options.nativeAstId,
    nativeSourceId: options.nativeSourceId,
    mappings,
    evidence: options.evidence ?? [],
    metadata: {
      generatedSpanStrategy: strategy,
      precision: 'declaration',
      sourceMapImplication: 'Approximate generated spans are emitted as sidecar mappings without rewriting the printer.',
      semanticIndexImplication: 'Semantic index linkage remains optional and can be attached through ids supplied in options.',
      lossAccountingImplication: 'The renderer does not create loss records; existing loss ids can be associated per semantic node.',
      mergeReadinessImplication: 'Declaration-block mappings can guide generated-output review but should not be treated as token-exact source maps.',
      ...(options.metadata ?? {})
    }
  });
}

function definedObject(object) {
  return Object.fromEntries(Object.entries(object).filter(([, value]) => value !== undefined));
}

function idFragment(value) {
  return safeIdentifier(String(value ?? 'unknown')).replace(/^_+/, '') || 'unknown';
}
